<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Razin-Anik" ignored="1" name="signup testing" tests="4" failures="1" timestamp="26 Apr 2020 12:22:42 GMT" time="13.78" errors="0">
  <testcase name="ctest" time="0.006" classname="scripts.codeRun"/>
  <testcase name="btest" time="0.001" classname="scripts.codeRun"/>
  <testcase name="validateElementPresent" time="4.251" classname="scripts.elementCheck"/>
  <testcase name="validateMessangerURL" time="1.769" classname="scripts.elementCheck">
    <failure type="java.lang.AssertionError" message="expected [https://www.mess.com/] but found [https://www.messenger.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.mess.com/] but found [https://www.messenger.com/]
	at scripts.elementCheck.validateMessangerURL(elementCheck.java:59)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- validateMessangerURL -->
  <testcase name="atest" time="0.0" classname="scripts.codeRun">
    <ignored/>
  </testcase> <!-- atest -->
</testsuite> <!-- signup testing -->
